/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PasswordCredentials struct for PasswordCredentials
type PasswordCredentials struct {
	// Username to authenticate with
	Username string `json:"username"`
	// Password to authenticate with
	Password string `json:"password,omitempty"`
}
