/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VidmConfigResponse struct for VidmConfigResponse
type VidmConfigResponse struct {
	// Fully quallified domain name of VMware Identity Manager
	VidmAppliance string `json:"vidm_appliance,omitempty"`
	// Client-id of the configured OAuth client
	ClientId string `json:"client_id,omitempty"`
	// True, if VMware Identity Manager integration is enabled
	Enable bool `json:"enable,omitempty"`
	// True, if SSL certificate check is enabled.
	CertificateValidationEnabled bool `json:"certificate_validation_enabled,omitempty"`
}
