/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// GroupAllOf struct for GroupAllOf
type GroupAllOf struct {
	Members []Reference `json:"members,omitempty"`
}
