/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ScopeEnum the model 'ScopeEnum'
type ScopeEnum string

// List of ScopeEnum
const (
	SCOPEENUM_UNIVERSAL ScopeEnum = "UNIVERSAL"
	SCOPEENUM_GLOBAL ScopeEnum = "GLOBAL"
	SCOPEENUM_LOCAL ScopeEnum = "LOCAL"
)
