/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// RouterDeviceAllOf struct for RouterDeviceAllOf
type RouterDeviceAllOf struct {
	Manager Reference `json:"manager,omitempty"`
}
