/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// GroupsMembersRequest struct for GroupsMembersRequest
type GroupsMembersRequest struct {
	EntityIds []string `json:"entity_ids,omitempty"`
	Cursor string `json:"cursor,omitempty"`
}
