/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// LicenseEdition Types for License Editions
type LicenseEdition string

// List of LicenseEdition
const (
	LICENSEEDITION_ADVANCED LicenseEdition = "ADVANCED"
	LICENSEEDITION_ENTERPRISE LicenseEdition = "ENTERPRISE"
	LICENSEEDITION_ROBO LicenseEdition = "ROBO"
	LICENSEEDITION_SDWAN LicenseEdition = "SDWAN"
	LICENSEEDITION_NAV LicenseEdition = "NAV"
)
