/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// IpV4Address struct for IpV4Address
type IpV4Address struct {
	IpAddress string `json:"ip_address,omitempty"`
	Netmask string `json:"netmask,omitempty"`
	NetworkAddress string `json:"network_address,omitempty"`
}
