/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AwsAccountManagerAllOf struct for AwsAccountManagerAllOf
type AwsAccountManagerAllOf struct {
	VendorId string `json:"vendor_id,omitempty"`
	ManagerId string `json:"manager_id,omitempty"`
}
