/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AwsDataSourceAllOf struct for AwsDataSourceAllOf
type AwsDataSourceAllOf struct {
	Credentials AwsCredentials `json:"credentials,omitempty"`
	// Whether or not to collect flows from the VPC Flow Logs
	FlowsEnabled bool `json:"flows_enabled,omitempty"`
	// Automatically add linked accounts
	AddLinkedAccounts bool `json:"add_linked_accounts,omitempty"`
	RoleArnSuffix string `json:"role_arn_suffix,omitempty"`
	// Should not be populated. Will be ignored if populated.
	LinkedRoleArn string `json:"linked_role_arn,omitempty"`
	// Should not be populated. Will be ignored if populated.
	DataSourceHierarchy string `json:"data_source_hierarchy,omitempty"`
	// Limit collection to only regions specified in selected_regions
	EnableAwsGeoRestrictions bool `json:"enable_aws_geo_restrictions,omitempty"`
	SelectedRegions []string `json:"selected_regions,omitempty"`
	// Should not be populated. Will be ignored if populated.
	ChildDatasourceCount int32 `json:"child_datasource_count,omitempty"`
	// Should not be populated. Will be ignored if populated.
	ChildDatasources []DataSourceEntityId `json:"child_datasources,omitempty"`
	// Identifier of web proxy to be used for connection. If not given or empty, any web proxy used earlier will be cleared
	WebProxyId string `json:"web_proxy_id,omitempty"`
}
