/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VCenterManagerAllOf struct for VCenterManagerAllOf
type VCenterManagerAllOf struct {
	IpAddress IpV4Address `json:"ip_address,omitempty"`
	Fqdn string `json:"fqdn,omitempty"`
	Vm Reference `json:"vm,omitempty"`
	NsxManager Reference `json:"nsx_manager,omitempty"`
	VcUuid string `json:"vc_uuid,omitempty"`
}
