/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Role Role assigned the user/group.
type Role string

// List of Role
const (
	ROLE_MEMBER Role = "MEMBER"
	ROLE_ADMIN Role = "ADMIN"
	ROLE_AUDITOR Role = "AUDITOR"
)
