/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// CollectorMapping Mappings for source collector (backup setup) to destination collector (restore setup)
type CollectorMapping struct {
	// Default collector_VM ip-address for mapping data sources, if no other collector mapping provided explicitly
	DefaultCollector string `json:"default_collector,omitempty"`
	Mappings []ObjectMapping `json:"mappings,omitempty"`
}
