/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VxlanLayer2Network struct for VxlanLayer2Network
type VxlanLayer2Network struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	NetworkAddresses []string `json:"network_addresses,omitempty"`
	Gateways []string `json:"gateways,omitempty"`
	SegmentId int32 `json:"segment_id,omitempty"`
	Vteps []Reference `json:"vteps,omitempty"`
	Scope ScopeEnum `json:"scope,omitempty"`
	NsxManagers []Reference `json:"nsx_managers,omitempty"`
}
