/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// IpAddressMembershipCriteria Ip Address membership definition
type IpAddressMembershipCriteria struct {
	IpAddresses []string `json:"ip_addresses,omitempty"`
}
