/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Aggregation struct for Aggregation
type Aggregation struct {
	Field string `json:"field,omitempty"`
	AggregationType string `json:"aggregation_type,omitempty"`
}
