/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// IpTag struct for IpTag
type IpTag struct {
	TagId string `json:"tag_id,omitempty"`
	Subnets []string `json:"subnets,omitempty"`
	IpAddressRanges []IpAddressRange `json:"ip_address_ranges,omitempty"`
}
