/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BucketValue struct for BucketValue
type BucketValue struct {
	Field string `json:"field,omitempty"`
	Value string `json:"value,omitempty"`
}
