/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VCenterManager struct for VCenterManager
type VCenterManager struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	IpAddress IpV4Address `json:"ip_address,omitempty"`
	Fqdn string `json:"fqdn,omitempty"`
	Vm Reference `json:"vm,omitempty"`
	NsxManager Reference `json:"nsx_manager,omitempty"`
	VcUuid string `json:"vc_uuid,omitempty"`
}
