/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BaseVirtualMachineAllOf struct for BaseVirtualMachineAllOf
type BaseVirtualMachineAllOf struct {
	IpAddresses []IpV4Address `json:"ip_addresses,omitempty"`
	// Default gateway IP of the VM
	DefaultGateway string `json:"default_gateway,omitempty"`
	Vnics []Reference `json:"vnics,omitempty"`
	SecurityGroups []Reference `json:"security_groups,omitempty"`
	SourceFirewallRules []RuleSet `json:"source_firewall_rules,omitempty"`
	DestinationFirewallRules []RuleSet `json:"destination_firewall_rules,omitempty"`
	IpSets []Reference `json:"ip_sets,omitempty"`
}
