/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Severity the model 'Severity'
type Severity string

// List of Severity
const (
	SEVERITY_CRITICAL Severity = "Critical"
	SEVERITY_MODERATE Severity = "Moderate"
	SEVERITY_WARNING Severity = "Warning"
	SEVERITY_INFO Severity = "Info"
)
