/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// FileServerType File Server type.
type FileServerType string

// List of FileServerType
const (
	FILESERVERTYPE_LOCAL FileServerType = "LOCAL"
	FILESERVERTYPE_SSH FileServerType = "SSH"
	FILESERVERTYPE_FTP FileServerType = "FTP"
)
