/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// DetailedVendorInfoResponse struct for DetailedVendorInfoResponse
type DetailedVendorInfoResponse struct {
	Results []DetailedVendorInfo `json:"results,omitempty"`
}
