/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxPolicyManagerAllOf struct for NsxPolicyManagerAllOf
type NsxPolicyManagerAllOf struct {
	IpAddress IpV4Address `json:"ip_address,omitempty"`
	DataSource Reference `json:"data_source,omitempty"`
	Fqdn string `json:"fqdn,omitempty"`
	EnforcementPoints []Reference `json:"enforcement_points,omitempty"`
	SddcType SddcType `json:"sddc_type,omitempty"`
	Sddc Reference `json:"sddc,omitempty"`
}
