/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SubscriptionResponse struct for SubscriptionResponse
type SubscriptionResponse struct {
	EntityId string `json:"entity_id,omitempty"`
	Active bool `json:"active,omitempty"`
	EventName string `json:"event_name,omitempty"`
	IsProblem bool `json:"is_problem,omitempty"`
	Severity Severity `json:"severity,omitempty"`
	SearchCriteria string `json:"search_criteria,omitempty"`
	GenerateEventCriteria GenerateEventCritera `json:"generate_event_criteria,omitempty"`
	EmailFrequency EmailFrequency `json:"email_frequency,omitempty"`
	DailyAtUtc string `json:"daily_at_utc,omitempty"`
	EmailIds []string `json:"email_ids,omitempty"`
	SnmpTrapEntityIds []string `json:"snmp_trap_entity_ids,omitempty"`
}
