/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// DistributedVirtualSwitchAllOf struct for DistributedVirtualSwitchAllOf
type DistributedVirtualSwitchAllOf struct {
	VendorId string `json:"vendor_id,omitempty"`
	VcenterManager Reference `json:"vcenter_manager,omitempty"`
	Hosts []Reference `json:"hosts,omitempty"`
}
