/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AzureAsgAllOf struct for AzureAsgAllOf
type AzureAsgAllOf struct {
	Vnet Reference `json:"vnet,omitempty"`
	Region string `json:"region,omitempty"`
	SecurityTags []Reference `json:"security_tags,omitempty"`
}
