/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Protocol the model 'Protocol'
type Protocol string

// List of Protocol
const (
	PROTOCOL_TCP Protocol = "TCP"
	PROTOCOL_UDP Protocol = "UDP"
	PROTOCOL_OTHER Protocol = "OTHER"
)
