/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SimplePortRange struct for SimplePortRange
type SimplePortRange struct {
	Start int32 `json:"start,omitempty"`
	End int32 `json:"end,omitempty"`
}
