/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Vpc struct for Vpc
type Vpc struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	CidrBlock IpV4Address `json:"cidr_block,omitempty"`
	State string `json:"state,omitempty"`
	Region string `json:"region,omitempty"`
	DefaultVpc bool `json:"default_vpc,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
	LastSynchedTime int64 `json:"last_synched_time,omitempty"`
}
