/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// LicensingResponse struct for LicensingResponse
type LicensingResponse struct {
	Result LicensingResponseResult `json:"result,omitempty"`
}
