/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BulkFetchResponse struct for BulkFetchResponse
type BulkFetchResponse struct {
	Results []EntityWithTime `json:"results,omitempty"`
}
