/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SecurityTagAllOf struct for SecurityTagAllOf
type SecurityTagAllOf struct {
	Description string `json:"description,omitempty"`
	DirectSecurityGroups []Reference `json:"direct_security_groups,omitempty"`
	SecurityGroups []Reference `json:"security_groups,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
	NsxManager Reference `json:"nsx_manager,omitempty"`
}
