/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AzureDataSourceRequestAllOf struct for AzureDataSourceRequestAllOf
type AzureDataSourceRequestAllOf struct {
	Credentials AzureCredentials `json:"credentials"`
	// Whether or not to collect flow data from the VNET Flow Logs
	FlowsEnabled bool `json:"flows_enabled,omitempty"`
	// Identifier of web proxy to be used for connection. If not given or empty, any web proxy used earlier will be cleared
	WebProxyId string `json:"web_proxy_id,omitempty"`
}
