/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// FlowTrafficType the model 'FlowTrafficType'
type FlowTrafficType string

// List of FlowTrafficType
const (
	FLOWTRAFFICTYPE_INTERNET_TRAFFIC FlowTrafficType = "INTERNET_TRAFFIC"
	FLOWTRAFFICTYPE_EAST_WEST_TRAFFIC FlowTrafficType = "EAST_WEST_TRAFFIC"
)
