/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SearchGroupByRequest struct for SearchGroupByRequest
type SearchGroupByRequest struct {
	EntityType AllEntityType `json:"entity_type,omitempty"`
	// query filter
	Filter string `json:"filter,omitempty"`
	Aggregations []Aggregation `json:"aggregations,omitempty"`
	GroupBy []string `json:"group_by,omitempty"`
	SortBy []AggregateOrderByClause `json:"sort_by,omitempty"`
	TimeRange TimeRange `json:"time_range,omitempty"`
	Size int32 `json:"size,omitempty"`
	Cursor string `json:"cursor,omitempty"`
}
