/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AzureNsgRuleAllOf struct for AzureNsgRuleAllOf
type AzureNsgRuleAllOf struct {
	Direction Ec2FirewallDirection `json:"direction,omitempty"`
}
