/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VersionResponse struct for VersionResponse
type VersionResponse struct {
	ApiVersion string `json:"api_version,omitempty"`
}
