/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Vlan struct for Vlan
type Vlan struct {
	Begin int32 `json:"begin,omitempty"`
	End int32 `json:"end,omitempty"`
}
