/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SortByClause struct for SortByClause
type SortByClause struct {
	Field string `json:"field,omitempty"`
	Order string `json:"order,omitempty"`
}
