/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ServiceNowDataSourceRequestAllOf struct for ServiceNowDataSourceRequestAllOf
type ServiceNowDataSourceRequestAllOf struct {
	Credentials PasswordCredentials `json:"credentials"`
	// Associated ServiceNow instance
	InstanceId string `json:"instance_id"`
	// CMDB configuration for CIs, relationships and graph traversal rules
	GraphConfiguration string `json:"graph_configuration,omitempty"`
	// Has graph configuration been modified from the default configuration
	IsGraphConfigCustomized bool `json:"is_graph_config_customized"`
	// Identifier of web proxy to be used for connection. If not given or empty, any web proxy used earlier will be cleared
	WebProxyId string `json:"web_proxy_id,omitempty"`
}
