/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// IpAddressRange struct for IpAddressRange
type IpAddressRange struct {
	StartIp string `json:"start_ip,omitempty"`
	EndIp string `json:"end_ip,omitempty"`
}
