/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// TopTalkerSortEnum the model 'TopTalkerSortEnum'
type TopTalkerSortEnum string

// List of TopTalkerSortEnum
const (
	TOPTALKERSORTENUM_FLOW_VOLUME TopTalkerSortEnum = "FLOW_VOLUME"
	TOPTALKERSORTENUM_FLOW_COUNT TopTalkerSortEnum = "FLOW_COUNT"
	TOPTALKERSORTENUM_TRAFFIC_RATE TopTalkerSortEnum = "TRAFFIC_RATE"
	TOPTALKERSORTENUM_SESSION_COUNT TopTalkerSortEnum = "SESSION_COUNT"
)
