/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Cluster struct for Cluster
type Cluster struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	// Total CPUs inside the cluster
	TotalCpus int32 `json:"total_cpus,omitempty"`
	// Total memory inside the cluster
	TotalMemory int64 `json:"total_memory,omitempty"`
	// Total CPU Cores inside the cluster
	NumCpuCores int32 `json:"num_cpu_cores,omitempty"`
	// Internal vCenter ID of the cluster
	VendorId string `json:"vendor_id,omitempty"`
	// Number of ESXi hosts in the cluster
	NumHosts int32 `json:"num_hosts,omitempty"`
	// Number of datastores in the cluster
	NumDatastores int32 `json:"num_datastores,omitempty"`
	NsxManager Reference `json:"nsx_manager,omitempty"`
	VcenterManager Reference `json:"vcenter_manager,omitempty"`
}
