/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ResourcePoolAllOf struct for ResourcePoolAllOf
type ResourcePoolAllOf struct {
	VcenterManager Reference `json:"vcenter_manager,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
}
