/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AzureCredentials struct for AzureCredentials
type AzureCredentials struct {
	// Azure Application Client ID to authenticate with
	AzureClient string `json:"azure_client"`
	// Azure Application Secret Key to authenticate with
	AzureKey string `json:"azure_key,omitempty"`
	// Azure Application Tenant ID to authenticate against
	AzureTenant string `json:"azure_tenant"`
	// Azure Application Subscription ID to authenticate against
	AzureSubscription string `json:"azure_subscription"`
}
