/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxipSetAllOf struct for NsxipSetAllOf
type NsxipSetAllOf struct {
	NsxManagers []Reference `json:"nsx_managers,omitempty"`
	Scope ScopeEnum `json:"scope,omitempty"`
}
