/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VidmCertificate struct for VidmCertificate
type VidmCertificate struct {
	// Root certificate of the VIDM server
	VidmRootCertificate string `json:"vidm_root_certificate,omitempty"`
}
