/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ApiError struct for ApiError
type ApiError struct {
	Code int32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
	Details []ErrorDetail `json:"details,omitempty"`
}
