/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AppFlowMetricEnum the model 'AppFlowMetricEnum'
type AppFlowMetricEnum string

// List of AppFlowMetricEnum
const (
	APPFLOWMETRICENUM_INCOMING_VOLUME AppFlowMetricEnum = "INCOMING_VOLUME"
	APPFLOWMETRICENUM_OUTGOING_VOLUME AppFlowMetricEnum = "OUTGOING_VOLUME"
)
