/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsGroupAllOf struct for NsGroupAllOf
type NsGroupAllOf struct {
	NsxtManagers []Reference `json:"nsxt_managers,omitempty"`
	IpSets []Reference `json:"ip_sets,omitempty"`
	SecurityTags []Reference `json:"security_tags,omitempty"`
}
