/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// MicroSecGroup struct for MicroSecGroup
type MicroSecGroup struct {
	Entity Reference `json:"entity,omitempty"`
}
