/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// UserResponse struct for UserResponse
type UserResponse struct {
	UserType UserType `json:"user_type,omitempty"`
	// Unique identifier assigned to user.
	Id string `json:"id,omitempty"`
	Role Role `json:"role,omitempty"`
	// Username of the user
	Username string `json:"username,omitempty"`
	// Domain name to which group belongs to.
	Domain string `json:"domain,omitempty"`
	// User's display name
	DisplayName string `json:"display_name,omitempty"`
}
