/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// LogicalRouterAllOf struct for LogicalRouterAllOf
type LogicalRouterAllOf struct {
	SubTypes []int32 `json:"sub_types,omitempty"`
	Manager Reference `json:"manager,omitempty"`
}
