/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// EntityPair struct for EntityPair
type EntityPair struct {
	// Source Entity Identifier
	SrcEntityId string `json:"src_entity_id,omitempty"`
	SrcEntityType EntityType `json:"src_entity_type,omitempty"`
	// Destination Entity Identifier
	DstEntityId string `json:"dst_entity_id,omitempty"`
	DstEntityType EntityType `json:"dst_entity_type,omitempty"`
}
