/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// DellSwitchDataSourceAllOf struct for DellSwitchDataSourceAllOf
type DellSwitchDataSourceAllOf struct {
	SwitchType DellSwitchType `json:"switch_type,omitempty"`
}
