/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AwsDataSource struct for AwsDataSource
type AwsDataSource struct {
	// Internal ID of data source, to be used in subsequent API calls
	EntityId string `json:"entity_id,omitempty"`
	EntityType DataSourceType `json:"entity_type,omitempty"`
	// IP address of data source (use either IP or FQDN, not both)
	Ip string `json:"ip,omitempty"`
	// Hostname of data source (use either IP or FQDN, not both)
	Fqdn string `json:"fqdn,omitempty"`
	// ID of Collector VM which should register this vcenter
	ProxyId string `json:"proxy_id,omitempty"`
	// A friendly nickname for the data source
	Nickname string `json:"nickname,omitempty"`
	// Whether or not data collection is enabled
	Enabled bool `json:"enabled,omitempty"`
	// Room for notes or comments about the data source
	Notes string `json:"notes,omitempty"`
	Credentials AwsCredentials `json:"credentials,omitempty"`
	// Whether or not to collect flows from the VPC Flow Logs
	FlowsEnabled bool `json:"flows_enabled,omitempty"`
	// Automatically add linked accounts
	AddLinkedAccounts bool `json:"add_linked_accounts,omitempty"`
	RoleArnSuffix string `json:"role_arn_suffix,omitempty"`
	// Should not be populated. Will be ignored if populated.
	LinkedRoleArn string `json:"linked_role_arn,omitempty"`
	// Should not be populated. Will be ignored if populated.
	DataSourceHierarchy string `json:"data_source_hierarchy,omitempty"`
	// Limit collection to only regions specified in selected_regions
	EnableAwsGeoRestrictions bool `json:"enable_aws_geo_restrictions,omitempty"`
	SelectedRegions []string `json:"selected_regions,omitempty"`
	// Should not be populated. Will be ignored if populated.
	ChildDatasourceCount int32 `json:"child_datasource_count,omitempty"`
	// Should not be populated. Will be ignored if populated.
	ChildDatasources []DataSourceEntityId `json:"child_datasources,omitempty"`
	// Identifier of web proxy to be used for connection. If not given or empty, any web proxy used earlier will be cleared
	WebProxyId string `json:"web_proxy_id,omitempty"`
}
