/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BulkUserDefinedProblemFetchResponse struct for BulkUserDefinedProblemFetchResponse
type BulkUserDefinedProblemFetchResponse struct {
	Results []UserDefinedProblemWithTime `json:"results,omitempty"`
}
