/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// EventMetaInfoResponse struct for EventMetaInfoResponse
type EventMetaInfoResponse struct {
	Results []EventMetaInfo `json:"results,omitempty"`
}
