/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PksDataSourceAllOf struct for PksDataSourceAllOf
type PksDataSourceAllOf struct {
	Credentials PasswordCredentials `json:"credentials,omitempty"`
	// Associated NSX-T Manager entity ID
	ManagerId string `json:"manager_id,omitempty"`
}
