/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxFirewallRuleAllOf struct for NsxFirewallRuleAllOf
type NsxFirewallRuleAllOf struct {
	LoggingEnabled bool `json:"logging_enabled,omitempty"`
	Direction FirewallDirection `json:"direction,omitempty"`
	Scope ScopeEnum `json:"scope,omitempty"`
	NsxManagers []Reference `json:"nsx_managers,omitempty"`
}
