/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AzureDataSourceAllOf struct for AzureDataSourceAllOf
type AzureDataSourceAllOf struct {
	Credentials AzureCredentials `json:"credentials,omitempty"`
	// Whether or not to collect flow data from the VNET Flow Logs
	FlowsEnabled bool `json:"flows_enabled,omitempty"`
	// Identifier of web proxy to be used for connection. If not given or empty, will clear any web proxy used earlier
	WebProxyId string `json:"web_proxy_id,omitempty"`
}
