/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VidmConfiguration struct for VidmConfiguration
type VidmConfiguration struct {
	// Provide fully quallified domain name of VMware Identity Manager
	VidmAppliance string `json:"vidm_appliance,omitempty"`
	// Provide rootCA certificate to trust. Can be generated using /vidm/licence
	RootCACertificate string `json:"rootCA_certificate,omitempty"`
	// Register VMware vRealize Network Insight as an OAuth client to VMware Identity Manager and provide client-id
	ClientId string `json:"client_id,omitempty"`
	// Provide the registered OAuth client secret
	ClientSecret string `json:"client_secret,omitempty"`
	// Optionally, provide SHA thumbprint to validate VMware Identity Manager appliance that is being configured
	ShaThumbprint string `json:"sha_thumbprint,omitempty"`
	// True, to enable the VMware Identity Manager integration in vRealize Network Insight
	Enable bool `json:"enable,omitempty"`
}
