/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ApplicationFlowData struct for ApplicationFlowData
type ApplicationFlowData struct {
	// The entity ID of the application this flow is attached
	ApplicationId string `json:"application_id,omitempty"`
	// The flow data
	FlowData []FlowData `json:"flow_data,omitempty"`
}
