/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// EdgeDeviceAllOf struct for EdgeDeviceAllOf
type EdgeDeviceAllOf struct {
	VendorId string `json:"vendor_id,omitempty"`
	Manager Reference `json:"manager,omitempty"`
}
