/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxvManagerDataSource struct for NsxvManagerDataSource
type NsxvManagerDataSource struct {
	// Internal ID of data source, to be used in subsequent API calls
	EntityId string `json:"entity_id,omitempty"`
	EntityType DataSourceType `json:"entity_type,omitempty"`
	// IP address of data source (use either IP or FQDN, not both)
	Ip string `json:"ip,omitempty"`
	// Hostname of data source (use either IP or FQDN, not both)
	Fqdn string `json:"fqdn,omitempty"`
	// ID of Collector VM which should register this vcenter
	ProxyId string `json:"proxy_id,omitempty"`
	// A friendly nickname for the data source
	Nickname string `json:"nickname,omitempty"`
	// Whether or not data collection is enabled
	Enabled bool `json:"enabled,omitempty"`
	// Room for notes or comments about the data source
	Notes string `json:"notes,omitempty"`
	Credentials PasswordCredentials `json:"credentials,omitempty"`
	// Associated vCenter data source entity ID
	VcenterId string `json:"vcenter_id,omitempty"`
	// Whether or not to configure NSX-v to send IPFIX to vRNI
	IpfixEnabled bool `json:"ipfix_enabled,omitempty"`
	// Whether or not collection via the Central CLI for ESG data is enabled
	CentralCliEnabled bool `json:"central_cli_enabled,omitempty"`
	// Whether or not to configure NSX-v to send virtual infrastructure latency metrics to vRNI
	LatencyEnabled bool `json:"latency_enabled,omitempty"`
}
