/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxSecurityGroupAllOf struct for NsxSecurityGroupAllOf
type NsxSecurityGroupAllOf struct {
	NsxManagers []Reference `json:"nsx_managers,omitempty"`
	Scope ScopeEnum `json:"scope,omitempty"`
	IpSets []Reference `json:"ip_sets,omitempty"`
	SecurityTags []Reference `json:"security_tags,omitempty"`
}
