/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BackupSchedule struct for BackupSchedule
type BackupSchedule struct {
	// True, to enable scheduled backup
	Enable bool `json:"enable,omitempty"`
	SchedulePeriod BackupSchedulePeriod `json:"schedule_period,omitempty"`
	// The minute at which backup needs to run (permitted values 0 - 59)
	Minute int32 `json:"minute,omitempty"`
	// The hour at which backup needs to run (permitted values 0 - 23)
	Hour int32 `json:"hour,omitempty"`
	// The day of the week when backup to be scheduled (permitted values 1{Sunday} - 7{Saturday})
	DayOfWeek int32 `json:"day_of_week,omitempty"`
}
