/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NodeId struct for NodeId
type NodeId struct {
	// Entity Identifier
	Id string `json:"id,omitempty"`
	EntityType NodeType `json:"entity_type,omitempty"`
}
