/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VpcAllOf struct for VpcAllOf
type VpcAllOf struct {
	CidrBlock IpV4Address `json:"cidr_block,omitempty"`
	State string `json:"state,omitempty"`
	Region string `json:"region,omitempty"`
	DefaultVpc bool `json:"default_vpc,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
	LastSynchedTime int64 `json:"last_synched_time,omitempty"`
}
