/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxDistributedFirewallAllOf struct for NsxDistributedFirewallAllOf
type NsxDistributedFirewallAllOf struct {
	VendorId string `json:"vendor_id,omitempty"`
}
