/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ProblemEventAllOf struct for ProblemEventAllOf
type ProblemEventAllOf struct {
	Severity string `json:"severity,omitempty"`
	EventCloseTimeEpochMs int64 `json:"event_close_time_epoch_ms,omitempty"`
}
