/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BaseServiceAllOf struct for BaseServiceAllOf
type BaseServiceAllOf struct {
	Protocol string `json:"protocol,omitempty"`
	PortRanges []PortRange `json:"port_ranges,omitempty"`
}
