/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ObjectMapping struct for ObjectMapping
type ObjectMapping struct {
	// Source object value
	Source string `json:"source,omitempty"`
	// Destination mapped value
	Destination string `json:"destination,omitempty"`
}
