/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// UserCredential struct for UserCredential
type UserCredential struct {
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
	Domain Domain `json:"domain,omitempty"`
}
