/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// DetailedVendorInfo struct for DetailedVendorInfo
type DetailedVendorInfo struct {
	EntityId string `json:"entity_id,omitempty"`
	EntityType string `json:"entity_type,omitempty"`
	EntityName string `json:"entity_name,omitempty"`
	VendorIds []VendorId `json:"vendor_ids,omitempty"`
	Manager VendorInfoWithMk `json:"manager,omitempty"`
}
