/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SubnetMappingList struct for SubnetMappingList
type SubnetMappingList struct {
	Results []SubnetMapping `json:"results,omitempty"`
}
