/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PagedListResponseWithTime struct for PagedListResponseWithTime
type PagedListResponseWithTime struct {
	Results []EntityIdWithTime `json:"results,omitempty"`
	// Cursor for the next page
	Cursor string `json:"cursor,omitempty"`
	// Total number of objects returned
	TotalCount int32 `json:"total_count,omitempty"`
	// Start timestamp of the window of the objects returned
	StartTime int64 `json:"start_time,omitempty"`
	// End timestamp of the window of the objects returned
	EndTime int64 `json:"end_time,omitempty"`
}
