/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ApplicationsMembersResponse struct for ApplicationsMembersResponse
type ApplicationsMembersResponse struct {
	Results []ApplicationMembersResponse `json:"results,omitempty"`
	Cursor string `json:"cursor,omitempty"`
	TotalCount int32 `json:"total_count,omitempty"`
}
