/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxtFirewallRuleAllOf struct for NsxtFirewallRuleAllOf
type NsxtFirewallRuleAllOf struct {
	AppliedTos []AppliedTo `json:"applied_tos,omitempty"`
}
