/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Snmp2cConfig struct for Snmp2cConfig
type Snmp2cConfig struct {
	// SNMPv2 Community string
	CommunityString string `json:"community_string,omitempty"`
}
