/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// KubernetesService struct for KubernetesService
type KubernetesService struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
	KubernetesCluster Reference `json:"kubernetes_cluster,omitempty"`
	Manager Reference `json:"manager,omitempty"`
	Annotations []string `json:"annotations,omitempty"`
	Labels []string `json:"labels,omitempty"`
	CreationTimestamp string `json:"creation_timestamp,omitempty"`
	Namespace Reference `json:"namespace,omitempty"`
	ClusterIp IpV4Address `json:"cluster_ip,omitempty"`
	LoadbalancerIp IpV4Address `json:"loadbalancer_ip,omitempty"`
	Type string `json:"type,omitempty"`
	ExternalIps []IpV4Address `json:"external_ips,omitempty"`
	Selectors []string `json:"selectors,omitempty"`
}
