/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// UserType The type of user.
type UserType string

// List of UserType
const (
	USERTYPE_LDAP UserType = "LDAP"
	USERTYPE_LOCAL UserType = "LOCAL"
	USERTYPE_VIDM UserType = "VIDM"
)
