/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VeloCloudDataSourceAllOf struct for VeloCloudDataSourceAllOf
type VeloCloudDataSourceAllOf struct {
	Credentials PasswordCredentials `json:"credentials,omitempty"`
	// Identifier of web proxy to be used for connection
	WebProxyId string `json:"web_proxy_id,omitempty"`
}
