/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxServiceAllOf struct for NsxServiceAllOf
type NsxServiceAllOf struct {
	NsxManagers []Reference `json:"nsx_managers,omitempty"`
	Scope ScopeEnum `json:"scope,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
}
