/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// CiscoSwitchDataSourceAllOf struct for CiscoSwitchDataSourceAllOf
type CiscoSwitchDataSourceAllOf struct {
	SwitchType CiscoSwitchType `json:"switch_type,omitempty"`
}
