/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Application struct for Application
type Application struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	// Timestamp of when the object was created
	CreateTime int64 `json:"create_time,omitempty"`
	// The username of who created the object
	CreatedBy string `json:"created_by,omitempty"`
	// Timestamp of when the object was last modified
	LastModifiedTime int64 `json:"last_modified_time,omitempty"`
	// The username of who last modified the object
	LastModifiedBy string `json:"last_modified_by,omitempty"`
}
