/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// DellSwitchType The Dell switch model type
type DellSwitchType string

// List of DellSwitchType
const (
	DELLSWITCHTYPE_FORCE_10_MXL_10 DellSwitchType = "FORCE_10_MXL_10"
	DELLSWITCHTYPE_POWERCONNECT_8024 DellSwitchType = "POWERCONNECT_8024"
	DELLSWITCHTYPE_S4048 DellSwitchType = "S4048"
	DELLSWITCHTYPE_Z9100 DellSwitchType = "Z9100"
	DELLSWITCHTYPE_S6000 DellSwitchType = "S6000"
)
