/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxRedirectRuleAllOf struct for NsxRedirectRuleAllOf
type NsxRedirectRuleAllOf struct {
	LoggingEnabled bool `json:"logging_enabled,omitempty"`
	Direction FirewallDirection `json:"direction,omitempty"`
	ServiceProfile string `json:"service_profile,omitempty"`
}
