/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// RecommendedRulesRequest struct for RecommendedRulesRequest
type RecommendedRulesRequest struct {
	Group1 MicroSecGroup `json:"group_1,omitempty"`
	Group2 MicroSecGroup `json:"group_2,omitempty"`
	TimeRange TimeRange `json:"time_range,omitempty"`
	// When True, includes ungrouped endpoints outside defined scope
	IncludeExternal bool `json:"include_external,omitempty"`
}
