/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ApplicationMembersResponse struct for ApplicationMembersResponse
type ApplicationMembersResponse struct {
	EntityId string `json:"entity_id,omitempty"`
	EntityType string `json:"entity_type,omitempty"`
	Name string `json:"name,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	CreationTime int64 `json:"creation_time,omitempty"`
	LastModifiedBy string `json:"last_modified_by,omitempty"`
	LastModifiedTime int64 `json:"last_modified_time,omitempty"`
	Source string `json:"source,omitempty"`
	Tiers []TierMembersResponse `json:"tiers,omitempty"`
}
