/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Cardinality struct for Cardinality
type Cardinality struct {
	Value int64 `json:"value,omitempty"`
	IsApprox bool `json:"is_approx,omitempty"`
}
