/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PathFirewallRules struct for PathFirewallRules
type PathFirewallRules struct {
	Firewalls []FirewallRuleSet `json:"firewalls,omitempty"`
}
