/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BaseFirewallManagerAllOf struct for BaseFirewallManagerAllOf
type BaseFirewallManagerAllOf struct {
	NsxManager Reference `json:"nsx_manager,omitempty"`
	Version string `json:"version,omitempty"`
	IpAddress IpV4Address `json:"ip_address,omitempty"`
}
