/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BackupRestoreRequest struct for BackupRestoreRequest
type BackupRestoreRequest struct {
	DataFilter ConfigDataFilter `json:"data_filter,omitempty"`
	BackupSchedule BackupSchedule `json:"backup_schedule,omitempty"`
	BackupFileServerType FileServerType `json:"backup_file_server_type,omitempty"`
	LocalFileServer LocalFileServer `json:"local_file_server,omitempty"`
	SshFileServer SshFileServer `json:"ssh_file_server,omitempty"`
	FtpFileServer FtpFileServer `json:"ftp_file_server,omitempty"`
	// True, to run backup now (on demand)
	ScheduleNow bool `json:"schedule_now,omitempty"`
	CollectorMapping CollectorMapping `json:"collector_mapping,omitempty"`
}
