/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxControllerDataCollection struct for NsxControllerDataCollection
type NsxControllerDataCollection struct {
	// Whether or not to collect data from the NSX-v Controller Cluster
	Enabled bool `json:"enabled,omitempty"`
	// Controller Password
	ControllerPassword string `json:"controller_password,omitempty"`
}
