/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// TestSnmpProfileResponse struct for TestSnmpProfileResponse
type TestSnmpProfileResponse struct {
	// Test trap sent successfully or not
	Status bool `json:"status,omitempty"`
	// Test SNMP trap status message
	Message string `json:"message,omitempty"`
}
