/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// RecommendedRule struct for RecommendedRule
type RecommendedRule struct {
	Sources []Reference `json:"sources,omitempty"`
	Destinations []Reference `json:"destinations,omitempty"`
	Protocols []string `json:"protocols,omitempty"`
	PortRanges []SimplePortRange `json:"port_ranges,omitempty"`
	Action string `json:"action,omitempty"`
}
