/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// LicenseUsageObject License usage objects
type LicenseUsageObject string

// List of LicenseUsageObject
const (
	LICENSEUSAGEOBJECT_V_MWARE_V_SPHERE LicenseUsageObject = "VMware vSphere"
	LICENSEUSAGEOBJECT_V_MWARE_CLOUD_ON_AWS LicenseUsageObject = "VMware Cloud on AWS"
	LICENSEUSAGEOBJECT_AWS LicenseUsageObject = "AWS"
	LICENSEUSAGEOBJECT_AZURE LicenseUsageObject = "Azure"
	LICENSEUSAGEOBJECT_PHYSICAL_I_PS LicenseUsageObject = "Physical IPs"
	LICENSEUSAGEOBJECT_SD_WAN LicenseUsageObject = "SD-WAN"
	LICENSEUSAGEOBJECT_NETWORKING_DEVICES LicenseUsageObject = "Networking Devices"
)
