/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// LicensingActivate struct for LicensingActivate
type LicensingActivate struct {
	Result VrniLicense `json:"result,omitempty"`
}
