/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// WebProxyRequest struct for WebProxyRequest
type WebProxyRequest struct {
	// Descriptor or identifier for particular web proxy. It should be unique
	NickName string `json:"nick_name,omitempty"`
	// IP address of web Proxy server
	TargetIp string `json:"target_ip,omitempty"`
	// Port number of web Proxy server
	TargetPort int32 `json:"target_port,omitempty"`
	// Type of web Proxy being configured. [Permitted Values - HTTP/HTTPS]
	ProxyType string `json:"proxy_type,omitempty"`
	// Type of authentication. [Permitted Values - Basic/NTLM]
	AuthType string `json:"auth_type,omitempty"`
	// Credentials required for this web proxy
	UseCredentials bool `json:"use_credentials,omitempty"`
	// Username for web proxy authentication
	UserName string `json:"user_name,omitempty"`
	// Password for web proxy authentication
	Password string `json:"password,omitempty"`
}
