/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// TierAllOf struct for TierAllOf
type TierAllOf struct {
	GroupMembershipCriteria []GroupMembershipCriteria `json:"group_membership_criteria,omitempty"`
	Application Reference `json:"application,omitempty"`
}
