/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VendorId struct for VendorId
type VendorId struct {
	IdType string `json:"id_type,omitempty"`
	IdValue string `json:"id_value,omitempty"`
}
