/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// UserGroupType The type of user-group.
type UserGroupType string

// List of UserGroupType
const (
	USERGROUPTYPE_LDAP UserGroupType = "LDAP"
	USERGROUPTYPE_LOCAL UserGroupType = "LOCAL"
	USERGROUPTYPE_VIDM UserGroupType = "VIDM"
)
