/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AwsCredentials struct for AwsCredentials
type AwsCredentials struct {
	// AWS Access Key to authenticate with
	AccessKey string `json:"access_key"`
	// AWS Secret Key to authenticate with
	SecretKey string `json:"secret_key,omitempty"`
}
