/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// EventMetaInfo struct for EventMetaInfo
type EventMetaInfo struct {
	EntityType string `json:"entity_type,omitempty"`
	Name string `json:"name,omitempty"`
	HelpText string `json:"help_text,omitempty"`
	Severity string `json:"severity,omitempty"`
	Tags []string `json:"tags,omitempty"`
	SupportedEntityTypes []string `json:"supported_entity_types,omitempty"`
	SupportedManagerTypes []string `json:"supported_manager_types,omitempty"`
	Impact string `json:"impact,omitempty"`
	Recommendations []string `json:"recommendations,omitempty"`
}
