/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// WebProxyMigrationRequest struct for WebProxyMigrationRequest
type WebProxyMigrationRequest struct {
	// Identifier of web proxy which needs migration
	SourceWebproxyId string `json:"source_webproxy_id,omitempty"`
	// Identifier of web proxy to which entities connected to source_webproxy_id will be migrated
	TargetWebproxyId string `json:"target_webproxy_id,omitempty"`
}
