/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VirtualMachine struct for VirtualMachine
type VirtualMachine struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	IpAddresses []IpV4Address `json:"ip_addresses,omitempty"`
	// Default gateway IP of the VM
	DefaultGateway string `json:"default_gateway,omitempty"`
	Vnics []Reference `json:"vnics,omitempty"`
	SecurityGroups []Reference `json:"security_groups,omitempty"`
	SourceFirewallRules []RuleSet `json:"source_firewall_rules,omitempty"`
	DestinationFirewallRules []RuleSet `json:"destination_firewall_rules,omitempty"`
	IpSets []Reference `json:"ip_sets,omitempty"`
	Cluster Reference `json:"cluster,omitempty"`
	ResourcePool Reference `json:"resource_pool,omitempty"`
	SecurityTags []Reference `json:"security_tags,omitempty"`
	Layer2Networks []Reference `json:"layer2_networks,omitempty"`
	Host Reference `json:"host,omitempty"`
	Vlans []Vlan `json:"vlans,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
	VcenterManager Reference `json:"vcenter_manager,omitempty"`
	Folders []Reference `json:"folders,omitempty"`
	Datastores []Reference `json:"datastores,omitempty"`
	Datacenter Reference `json:"datacenter,omitempty"`
	NsxManager Reference `json:"nsx_manager,omitempty"`
	SourceInversionRules []RuleSet `json:"source_inversion_rules,omitempty"`
	DestinationInversionRules []RuleSet `json:"destination_inversion_rules,omitempty"`
	// Number of vCPUs this VM has
	CpuCount int32 `json:"cpu_count,omitempty"`
	// Amount of memory this VM has
	Memory int32 `json:"memory,omitempty"`
}
