/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PolicyManagerFirewallAllOf struct for PolicyManagerFirewallAllOf
type PolicyManagerFirewallAllOf struct {
	FirewallSections []Reference `json:"firewall_sections,omitempty"`
	SddcType SddcType `json:"sddc_type,omitempty"`
}
