/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SnmpProfileListResponse struct for SnmpProfileListResponse
type SnmpProfileListResponse struct {
	Results []SnmpProfileResponse `json:"results,omitempty"`
	TotalCount int32 `json:"total_count,omitempty"`
}
