/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Node struct for Node
type Node struct {
	Id string `json:"id,omitempty"`
	EntityType NodeType `json:"entity_type,omitempty"`
	NodeType string `json:"node_type,omitempty"`
	NodeId string `json:"node_id,omitempty"`
	IpAddress string `json:"ip_address,omitempty"`
	Name string `json:"name,omitempty"`
}
