/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// FlowData struct for FlowData
type FlowData struct {
	Name string `json:"name,omitempty"`
	Value float32 `json:"value,omitempty"`
}
