/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// TierRequest struct for TierRequest
type TierRequest struct {
	Name string `json:"name,omitempty"`
	GroupMembershipCriteria []GroupMembershipCriteria `json:"group_membership_criteria,omitempty"`
}
