/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// DataSourceType the model 'DataSourceType'
type DataSourceType string

// List of DataSourceType
const (
	DATASOURCETYPE_CISCO_SWITCH_DATA_SOURCE DataSourceType = "CiscoSwitchDataSource"
	DATASOURCETYPE_DELL_SWITCH_DATA_SOURCE DataSourceType = "DellSwitchDataSource"
	DATASOURCETYPE_ARISTA_SWITCH_DATA_SOURCE DataSourceType = "AristaSwitchDataSource"
	DATASOURCETYPE_BROCADE_SWITCH_DATA_SOURCE DataSourceType = "BrocadeSwitchDataSource"
	DATASOURCETYPE_JUNIPER_SWITCH_DATA_SOURCE DataSourceType = "JuniperSwitchDataSource"
	DATASOURCETYPE_GD_DATA_SOURCE DataSourceType = "GDDataSource"
	DATASOURCETYPE_F5_BIGIP_DATA_SOURCE DataSourceType = "F5BIGIPDataSource"
	DATASOURCETYPE_NSXALB_DATA_SOURCE DataSourceType = "NSXALBDataSource"
	DATASOURCETYPE_HUAWEI_SWITCH_DATA_SOURCE DataSourceType = "HuaweiSwitchDataSource"
	DATASOURCETYPE_MELLANOX_SWITCH_DATA_SOURCE DataSourceType = "MellanoxSwitchDataSource"
	DATASOURCETYPE_HPE_SWITCH_DATA_SOURCE DataSourceType = "HPESwitchDataSource"
	DATASOURCETYPE_CISCO_ASRXR_DATA_SOURCE DataSourceType = "CiscoASRXRDataSource"
	DATASOURCETYPE_UANI_DATA_SOURCE DataSourceType = "UANIDataSource"
	DATASOURCETYPE_V_CENTER_DATA_SOURCE DataSourceType = "VCenterDataSource"
	DATASOURCETYPE_NSXV_MANAGER_DATA_SOURCE DataSourceType = "NSXVManagerDataSource"
	DATASOURCETYPE_UCS_MANAGER_DATA_SOURCE DataSourceType = "UCSManagerDataSource"
	DATASOURCETYPE_HPVC_MANAGER_DATA_SOURCE DataSourceType = "HPVCManagerDataSource"
	DATASOURCETYPE_HP_ONE_VIEW_DATA_SOURCE DataSourceType = "HPOneViewDataSource"
	DATASOURCETYPE_PAN_FIREWALL_DATA_SOURCE DataSourceType = "PanFirewallDataSource"
	DATASOURCETYPE_CHECKPOINT_FIREWALL_DATA_SOURCE DataSourceType = "CheckpointFirewallDataSource"
	DATASOURCETYPE_FORTINET_FIREWALL_DATA_SOURCE DataSourceType = "FortinetFirewallDataSource"
	DATASOURCETYPE_NSXT_MANAGER_DATA_SOURCE DataSourceType = "NSXTManagerDataSource"
	DATASOURCETYPE_KUBERNETES_DATA_SOURCE DataSourceType = "KubernetesDataSource"
	DATASOURCETYPE_PKS_DATA_SOURCE DataSourceType = "PKSDataSource"
	DATASOURCETYPE_INFOBLOX_MANAGER_DATA_SOURCE DataSourceType = "InfobloxManagerDataSource"
	DATASOURCETYPE_CISCO_ACI_DATA_SOURCE DataSourceType = "CiscoACIDataSource"
	DATASOURCETYPE_SERVICE_NOW_DATA_SOURCE DataSourceType = "ServiceNowDataSource"
	DATASOURCETYPE_POLICY_MANAGER_DATA_SOURCE DataSourceType = "PolicyManagerDataSource"
	DATASOURCETYPE_AZURE_DATA_SOURCE DataSourceType = "AzureDataSource"
	DATASOURCETYPE_VELO_CLOUD_DATA_SOURCE DataSourceType = "VeloCloudDataSource"
	DATASOURCETYPE_AWS_DATA_SOURCE DataSourceType = "AWSDataSource"
	DATASOURCETYPE_HCX_DATA_SOURCE DataSourceType = "HcxDataSource"
)
