/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// MetricResponse struct for MetricResponse
type MetricResponse struct {
	Metric string `json:"metric,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Interval int32 `json:"interval,omitempty"`
	Unit string `json:"unit,omitempty"`
	Pointlist [][]float64 `json:"pointlist,omitempty"`
	Start int64 `json:"start,omitempty"`
	End int64 `json:"end,omitempty"`
}
