/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// MetaEntityType the model 'MetaEntityType'
type MetaEntityType string

// List of MetaEntityType
const (
	METAENTITYTYPE_GROUP MetaEntityType = "Group"
	METAENTITYTYPE_BASE_SECURITY_GROUP MetaEntityType = "BaseSecurityGroup"
	METAENTITYTYPE_BASE_EVENT MetaEntityType = "BaseEvent"
	METAENTITYTYPE_BASE_VIRTUAL_MACHINE MetaEntityType = "BaseVirtualMachine"
	METAENTITYTYPE_BASE_FIREWALL_RULE MetaEntityType = "BaseFirewallRule"
	METAENTITYTYPE_BASE_IP_SET MetaEntityType = "BaseIPSet"
	METAENTITYTYPE_BASE_L2_NETWORK MetaEntityType = "BaseL2Network"
	METAENTITYTYPE_BASE_MANAGER MetaEntityType = "BaseManager"
	METAENTITYTYPE_BASE_FIREWALL_MANAGER MetaEntityType = "BaseFirewallManager"
	METAENTITYTYPE_BASE_GENERIC_FIREWALL MetaEntityType = "BaseGenericFirewall"
	METAENTITYTYPE_BASE_GENERIC_FIREWALL_RULE MetaEntityType = "BaseGenericFirewallRule"
	METAENTITYTYPE_BASE_NSX_MANAGER MetaEntityType = "BaseNSXManager"
	METAENTITYTYPE_BASE_FIREWALL MetaEntityType = "BaseFirewall"
	METAENTITYTYPE_BASE_SERVICE MetaEntityType = "BaseService"
	METAENTITYTYPE_BASE_SERVICE_GROUP MetaEntityType = "BaseServiceGroup"
	METAENTITYTYPE_BASE_VNIC MetaEntityType = "BaseVnic"
)
