/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// TierMembersResponse struct for TierMembersResponse
type TierMembersResponse struct {
	EntityId string `json:"entity_id,omitempty"`
	EntityType string `json:"entity_type,omitempty"`
	Name string `json:"name,omitempty"`
	Members []ApplicationMember `json:"members,omitempty"`
}
