/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// LicenseUsageCapacity Capacity types for license usage
type LicenseUsageCapacity string

// List of LicenseUsageCapacity
const (
	LICENSEUSAGECAPACITY_CP_US LicenseUsageCapacity = "CPUs"
	LICENSEUSAGECAPACITY_V_MS LicenseUsageCapacity = "VMs"
	LICENSEUSAGECAPACITY_EDGES LicenseUsageCapacity = "Edges"
	LICENSEUSAGECAPACITY_DEVICES LicenseUsageCapacity = "Devices"
	LICENSEUSAGECAPACITY_I_PS LicenseUsageCapacity = "IPs"
	LICENSEUSAGECAPACITY_V_CP_US LicenseUsageCapacity = "vCPUs"
	LICENSEUSAGECAPACITY_HOSTS LicenseUsageCapacity = "Hosts"
)
