/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// KubernetesDataSourceRequestAllOf struct for KubernetesDataSourceRequestAllOf
type KubernetesDataSourceRequestAllOf struct {
	Credentials K8SCredentials `json:"credentials"`
	// Associated NSX-T data source entity Id
	ManagerId string `json:"manager_id"`
}
