/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxServiceGroupAllOf struct for NsxServiceGroupAllOf
type NsxServiceGroupAllOf struct {
	Scope ScopeEnum `json:"scope,omitempty"`
	NsxManagers []Reference `json:"nsx_managers,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
}
