/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BackupRestoreStatusResponse struct for BackupRestoreStatusResponse
type BackupRestoreStatusResponse struct {
	// Status of currently executing or last backup-restore job
	Status string `json:"status,omitempty"`
	// File name of backup tar file
	BackupFileName string `json:"backup_file_name,omitempty"`
	// TimeStamp of the last status update
	StatusUpdatedTimestamp string `json:"status_updated_timestamp,omitempty"`
	// List of components failed to backup or restore
	FailedComponents []string `json:"failed_components,omitempty"`
}
