/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PolicyManagerDataSourceRequestAllOf struct for PolicyManagerDataSourceRequestAllOf
type PolicyManagerDataSourceRequestAllOf struct {
	// Cloud Services Portal API Refresh Token. You can generate this via the CSP UI under My Account and API Tokens.
	CspRefreshToken string `json:"csp_refresh_token,omitempty"`
	// Associated vcenter data source entity ID
	VcenterId string `json:"vcenter_id"`
	// Whether or not to configure NSX-T to send IPFIX to vRNI
	IpfixEnabled bool `json:"ipfix_enabled,omitempty"`
	// Identifier of web proxy to be used for connection. If not given or empty, any web proxy used earlier will be cleared
	WebProxyId string `json:"web_proxy_id,omitempty"`
}
