/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// UserUpdateRequest struct for UserUpdateRequest
type UserUpdateRequest struct {
	Username string `json:"username,omitempty"`
	NewPassword string `json:"new_password,omitempty"`
}
