/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ErrorDetail struct for ErrorDetail
type ErrorDetail struct {
	Code int32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
	Target []string `json:"target,omitempty"`
}
