/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AuditRequest struct for AuditRequest
type AuditRequest struct {
	// Username making the change
	UserName string `json:"user_name,omitempty"`
	// Client IP that is making the change
	IpAddress string `json:"ip_address,omitempty"`
	// Entity Type of object being changed
	EntityType string `json:"entity_type,omitempty"`
	// Entity ID of object being changed
	EntityId string `json:"entity_id,omitempty"`
	// Operation on object being changed
	Operation string `json:"operation,omitempty"`
	// Response from vRNI, whether it's successfull or not
	Response string `json:"response,omitempty"`
	Size int32 `json:"size,omitempty"`
	// Cursor for the next page of logs
	Cursor string `json:"cursor,omitempty"`
	TimeRange TimeRange `json:"time_range,omitempty"`
}
