/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ApplicationMembers struct for ApplicationMembers
type ApplicationMembers struct {
	Results []ApplicationMember `json:"results,omitempty"`
	Cursor string `json:"cursor,omitempty"`
}
