/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BaseGenericFirewallRuleAllOf struct for BaseGenericFirewallRuleAllOf
type BaseGenericFirewallRuleAllOf struct {
	Direction FirewallDirection `json:"direction,omitempty"`
}
