/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// WebProxyConfigListForNodes struct for WebProxyConfigListForNodes
type WebProxyConfigListForNodes struct {
	Results []WebProxyConfigForNode `json:"results,omitempty"`
}
