/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Snmp3Config struct for Snmp3Config
type Snmp3Config struct {
	// SNMPv3 Username
	Username string `json:"username,omitempty"`
	// SNMPv3 Context name
	ContextName string `json:"context_name,omitempty"`
	// SNMPv3 Authentication type
	AuthenticationType string `json:"authentication_type,omitempty"`
	// SNMPv3 Authentication password
	AuthenticationPassword string `json:"authentication_password,omitempty"`
	// SNMPv3 Privacy password type
	PrivacyType string `json:"privacy_type,omitempty"`
	// SNMPv3 Pricacy password
	PrivacyPassword string `json:"privacy_password,omitempty"`
}
