/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BaseVnicAllOf struct for BaseVnicAllOf
type BaseVnicAllOf struct {
	IpAddresses []IpV4Address `json:"ip_addresses,omitempty"`
	Layer2Network Reference `json:"layer2_network,omitempty"`
	Vlan Vlan `json:"vlan,omitempty"`
	Vm Reference `json:"vm,omitempty"`
}
