/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxPolicyGroupAllOf struct for NsxPolicyGroupAllOf
type NsxPolicyGroupAllOf struct {
	RealizedEntities []Reference `json:"realized_entities,omitempty"`
	SddcType SddcType `json:"sddc_type,omitempty"`
}
