/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// LicenseCapacityType License entitlement types
type LicenseCapacityType string

// List of LicenseCapacityType
const (
	LICENSECAPACITYTYPE_CPU LicenseCapacityType = "CPU"
	LICENSECAPACITYTYPE_CCU LicenseCapacityType = "CCU"
	LICENSECAPACITYTYPE_VM LicenseCapacityType = "VM"
	LICENSECAPACITYTYPE_CORE LicenseCapacityType = "CORE"
	LICENSECAPACITYTYPE_TEN_MBPS LicenseCapacityType = "TEN_MBPS"
	LICENSECAPACITYTYPE_THIRTY_MBPS LicenseCapacityType = "THIRTY_MBPS"
	LICENSECAPACITYTYPE_FIFTY_MBPS LicenseCapacityType = "FIFTY_MBPS"
	LICENSECAPACITYTYPE_HUNDRED_MBPS LicenseCapacityType = "HUNDRED_MBPS"
	LICENSECAPACITYTYPE_TWO_HUNDRED_MBPS LicenseCapacityType = "TWO_HUNDRED_MBPS"
	LICENSECAPACITYTYPE_FIVE_HUNDRED_MBPS LicenseCapacityType = "FIVE_HUNDRED_MBPS"
	LICENSECAPACITYTYPE_ONE_GBPS LicenseCapacityType = "ONE_GBPS"
	LICENSECAPACITYTYPE_TWO_GBPS LicenseCapacityType = "TWO_GBPS"
	LICENSECAPACITYTYPE_FIVE_GBPS LicenseCapacityType = "FIVE_GBPS"
	LICENSECAPACITYTYPE_TEN_GBPS LicenseCapacityType = "TEN_GBPS"
	LICENSECAPACITYTYPE_THREE_FIFTY_MBPS LicenseCapacityType = "THREE_FIFTY_MBPS"
	LICENSECAPACITYTYPE_SEVEN_FIFTY_MBPS LicenseCapacityType = "SEVEN_FIFTY_MBPS"
	LICENSECAPACITYTYPE_DEVICE LicenseCapacityType = "DEVICE"
)
