/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ApplicationAllOf struct for ApplicationAllOf
type ApplicationAllOf struct {
	// Timestamp of when the object was created
	CreateTime int64 `json:"create_time,omitempty"`
	// The username of who created the object
	CreatedBy string `json:"created_by,omitempty"`
	// Timestamp of when the object was last modified
	LastModifiedTime int64 `json:"last_modified_time,omitempty"`
	// The username of who last modified the object
	LastModifiedBy string `json:"last_modified_by,omitempty"`
}
