/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// EntityMetricsSchema struct for EntityMetricsSchema
type EntityMetricsSchema struct {
	Results []MetricSchema `json:"results,omitempty"`
}
