/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// FirewallDirection the model 'FirewallDirection'
type FirewallDirection string

// List of FirewallDirection
const (
	FIREWALLDIRECTION_IN FirewallDirection = "IN"
	FIREWALLDIRECTION_OUT FirewallDirection = "OUT"
	FIREWALLDIRECTION_INOUT FirewallDirection = "INOUT"
)
