/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ProxyResponse struct for ProxyResponse
type ProxyResponse struct {
	// Entity Identifier for a web proxy server
	ProxyId string `json:"proxy_id,omitempty"`
	// Descriptor or identifier for particular web proxy.
	NickName string `json:"nick_name,omitempty"`
	// IP address of web Proxy server
	TargetIp string `json:"target_ip,omitempty"`
	// Port number of web Proxy server
	TargetPort int32 `json:"target_port,omitempty"`
	// Number of connected entities to a web proxy
	ConnectedEntities int32 `json:"connected_entities,omitempty"`
	// Type of web proxy
	ProxyType string `json:"proxy_type,omitempty"`
	// Type of authentication
	AuthType string `json:"auth_type,omitempty"`
	// Whether credentials were used earlier when web proxy was configured
	UseCredentials bool `json:"use_credentials,omitempty"`
	// Username of the authenticated web proxy
	UserName string `json:"user_name,omitempty"`
	// Can the web proxy be edited or deleted from the UI
	IsModifiable bool `json:"is_modifiable,omitempty"`
}
