/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SubnetMappingAllOf struct for SubnetMappingAllOf
type SubnetMappingAllOf struct {
	Cidr string `json:"cidr,omitempty"`
	VlanId int32 `json:"vlan_id,omitempty"`
}
