/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// WebProxyConfigForNode struct for WebProxyConfigForNode
type WebProxyConfigForNode struct {
	// vRNI Node Identifier (Collector or Platform)
	NodeId string `json:"node_id,omitempty"`
	// Entity Identifier for a web proxy server
	WebProxyId string `json:"web_proxy_id,omitempty"`
	// Descriptor or identifier for particular web proxy.
	WebNickName string `json:"web_nick_name,omitempty"`
}
