/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ProxyListResponse struct for ProxyListResponse
type ProxyListResponse struct {
	Results []ProxyResponse `json:"results,omitempty"`
}
