/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VrniLicense struct for VrniLicense
type VrniLicense struct {
	ProductName string `json:"productName,omitempty"`
	// true if license is evaluation license
	Evaluation bool `json:"evaluation,omitempty"`
	// license serial key
	LicenseKey string `json:"licenseKey,omitempty"`
	// sockets entitlement for this license
	NumberOfSockets int32 `json:"numberOfSockets,omitempty"`
	// service tag
	ServiceTag string `json:"serviceTag,omitempty"`
	// environment deployment type
	DeploymentType string `json:"deploymentType,omitempty"`
	CapacityType LicenseCapacityType `json:"capacityType,omitempty"`
	Edition LicenseEdition `json:"edition,omitempty"`
	// true if customer state is suspended
	Suspended bool `json:"suspended,omitempty"`
	// true if customer state is deleted
	Deleted bool `json:"deleted,omitempty"`
	// true for license keys from last version, which are active only for grace period
	Invalid bool `json:"invalid,omitempty"`
	// list of entitlements supported by the license
	Entitlements []VrniLicenseEntitlements `json:"entitlements,omitempty"`
}
