/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SddcType the model 'SddcType'
type SddcType string

// List of SddcType
const (
	SDDCTYPE_ONPREM SddcType = "ONPREM"
	SDDCTYPE_VMC SddcType = "VMC"
)
