/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ApplicationRequest struct for ApplicationRequest
type ApplicationRequest struct {
	// The name of the application
	Name string `json:"name"`
}
