/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Ec2FirewallDirection the model 'Ec2FirewallDirection'
type Ec2FirewallDirection string

// List of EC2FirewallDirection
const (
	EC2FIREWALLDIRECTION_INBOUND Ec2FirewallDirection = "INBOUND"
	EC2FIREWALLDIRECTION_OUTBOUND Ec2FirewallDirection = "OUTBOUND"
)
