/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AggregationWithValue struct for AggregationWithValue
type AggregationWithValue struct {
	Field string `json:"field,omitempty"`
	AggregationType string `json:"aggregation_type,omitempty"`
	Value float64 `json:"value,omitempty"`
}
