/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SwitchDataSourceRequestAllOf struct for SwitchDataSourceRequestAllOf
type SwitchDataSourceRequestAllOf struct {
	Credentials PasswordCredentials `json:"credentials,omitempty"`
}
