/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NameRequestParam struct for NameRequestParam
type NameRequestParam struct {
	EntityId string `json:"entity_id,omitempty"`
	Time int64 `json:"time,omitempty"`
}
