/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// IpEndpointAllOf struct for IpEndpointAllOf
type IpEndpointAllOf struct {
	IpAddress IpV4Address `json:"ip_address,omitempty"`
	Fqdns []string `json:"fqdns,omitempty"`
}
