/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// GenerateEventCritera the model 'GenerateEventCritera'
type GenerateEventCritera string

// List of GenerateEventCritera
const (
	GENERATEEVENTCRITERA_SEARCH_RESULT_CHANGE GenerateEventCritera = "SEARCH_RESULT_CHANGE"
	GENERATEEVENTCRITERA_ZERO_SEARCH_RESULTS GenerateEventCritera = "ZERO_SEARCH_RESULTS"
)
