/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PolicyManagerDataSource struct for PolicyManagerDataSource
type PolicyManagerDataSource struct {
	// Internal ID of data source, to be used in subsequent API calls
	EntityId string `json:"entity_id,omitempty"`
	EntityType DataSourceType `json:"entity_type,omitempty"`
	// IP address of data source (use either IP or FQDN, not both)
	Ip string `json:"ip,omitempty"`
	// Hostname of data source (use either IP or FQDN, not both)
	Fqdn string `json:"fqdn,omitempty"`
	// ID of Collector VM which should register this vcenter
	ProxyId string `json:"proxy_id,omitempty"`
	// A friendly nickname for the data source
	Nickname string `json:"nickname,omitempty"`
	// Whether or not data collection is enabled
	Enabled bool `json:"enabled,omitempty"`
	// Room for notes or comments about the data source
	Notes string `json:"notes,omitempty"`
	// Cloud Services Portal API Refresh Token. You can generate this via the CSP UI under My Account and API Tokens.
	CspRefreshToken string `json:"csp_refresh_token,omitempty"`
	// Associated vcenter data source entity ID
	VcenterId string `json:"vcenter_id,omitempty"`
	// Whether or not to configure NSX-T to send IPFIX to vRNI
	IpfixEnabled bool `json:"ipfix_enabled,omitempty"`
	// Identifier of web proxy to be used for connection
	WebProxyId string `json:"web_proxy_id,omitempty"`
}
