/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxtManager struct for NsxtManager
type NsxtManager struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	Fqdn string `json:"fqdn,omitempty"`
	IpAddress IpV4Address `json:"ip_address,omitempty"`
	Version string `json:"version,omitempty"`
}
