/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BaseL2NetworkAllOf struct for BaseL2NetworkAllOf
type BaseL2NetworkAllOf struct {
	NetworkAddresses []string `json:"network_addresses,omitempty"`
	Gateways []string `json:"gateways,omitempty"`
}
