/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsServiceAllOf struct for NsServiceAllOf
type NsServiceAllOf struct {
	NsxtManagers []Reference `json:"nsxt_managers,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
}
