/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// LocalFileServer struct for LocalFileServer
type LocalFileServer struct {
	// Directory on file server to store/fetch backups
	BackupDirectory string `json:"backup_directory,omitempty"`
	// filename of the backup to be restored (used during restore only)
	BackupFileName string `json:"backup_file_name,omitempty"`
}
