/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// CloudNetworkAllOf struct for CloudNetworkAllOf
type CloudNetworkAllOf struct {
	PeerCloudNetworks []Reference `json:"peer_cloud_networks,omitempty"`
	AddressSpaces []IpV4Address `json:"address_spaces,omitempty"`
	ProvisionedState string `json:"provisioned_state,omitempty"`
	Regions []string `json:"regions,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
}
