/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Ec2SecurityGroupAllOf struct for Ec2SecurityGroupAllOf
type Ec2SecurityGroupAllOf struct {
	Vpc Reference `json:"vpc,omitempty"`
	Region string `json:"region,omitempty"`
}
