/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// TierListResponse struct for TierListResponse
type TierListResponse struct {
	Results []Tier `json:"results,omitempty"`
}
