/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// CloudNetwork struct for CloudNetwork
type CloudNetwork struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	PeerCloudNetworks []Reference `json:"peer_cloud_networks,omitempty"`
	AddressSpaces []IpV4Address `json:"address_spaces,omitempty"`
	ProvisionedState string `json:"provisioned_state,omitempty"`
	Regions []string `json:"regions,omitempty"`
	VendorId string `json:"vendor_id,omitempty"`
}
