/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VrniLicenseEntitlements struct for VrniLicenseEntitlements
type VrniLicenseEntitlements struct {
	CapacityType LicenseCapacityType `json:"capacityType,omitempty"`
	// capacity count for entitlement
	Count int32 `json:"count,omitempty"`
}
