/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// FlowSummary struct for FlowSummary
type FlowSummary struct {
	// Incoming traffic in bytes
	IngressBytes int64 `json:"ingress_bytes,omitempty"`
	// Outgoing traffic in bytes
	EgressBytes int64 `json:"egress_bytes,omitempty"`
}
