/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// DatasourceHealth Datasource Health state
type DatasourceHealth struct {
	// Is the data source healthy and data is being collected?
	HealthStatus string `json:"health_status,omitempty"`
	// Message for when the data source is not healthy
	HealthMessage string `json:"health_message,omitempty"`
	HealthErrorCode string `json:"health_error_code,omitempty"`
}
