/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// RuleSet struct for RuleSet
type RuleSet struct {
	Rules []Reference `json:"rules,omitempty"`
	Firewall Reference `json:"firewall,omitempty"`
	RuleSetType string `json:"rule_set_type,omitempty"`
}
