/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AuditResponse struct for AuditResponse
type AuditResponse struct {
	IpAddress string `json:"ip_address,omitempty"`
	UserName string `json:"user_name,omitempty"`
	EntityType string `json:"entity_type,omitempty"`
	EntityId string `json:"entity_id,omitempty"`
	Operation string `json:"operation,omitempty"`
	Response string `json:"response,omitempty"`
	Value string `json:"value,omitempty"`
	Timestamp int64 `json:"timestamp,omitempty"`
}
