/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// EmailFrequency the model 'EmailFrequency'
type EmailFrequency string

// List of EmailFrequency
const (
	EMAILFREQUENCY_IMMEDIATELY EmailFrequency = "IMMEDIATELY"
	EMAILFREQUENCY_DAILY_DIGEST EmailFrequency = "DAILY_DIGEST"
)
