/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// IpTagIdList struct for IpTagIdList
type IpTagIdList struct {
	TagIds []string `json:"tag_ids,omitempty"`
}
