/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PathFirewallRulesRequest struct for PathFirewallRulesRequest
type PathFirewallRulesRequest struct {
	// Source IP configured in firewall rule
	SourceIpAddress string `json:"source_ip_address,omitempty"`
	// Destination IP configured in firewall rule
	DestinationIpAddress string `json:"destination_ip_address,omitempty"`
	// Port number configured in firewall rule
	Port int32 `json:"port,omitempty"`
	// Protocol configured in firewall rule
	Protocol string `json:"protocol,omitempty"`
	// Timestamp of object
	Time int64 `json:"time,omitempty"`
}
