/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AzureSubscriptionAllOf struct for AzureSubscriptionAllOf
type AzureSubscriptionAllOf struct {
	VendorId string `json:"vendor_id,omitempty"`
	SecondaryId string `json:"secondary_id,omitempty"`
	ManagerId string `json:"manager_id,omitempty"`
}
