/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// FirewallRuleMaskEventAllOf struct for FirewallRuleMaskEventAllOf
type FirewallRuleMaskEventAllOf struct {
	MaskedRule Reference `json:"maskedRule,omitempty"`
	MaskingRule Reference `json:"maskingRule,omitempty"`
}
