/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VidmOauthClientResponse struct for VidmOauthClientResponse
type VidmOauthClientResponse struct {
	// Fully quallified domain name of VMware Identity Manager configured in vRealize Network Insight
	VidmAppliance string `json:"vidm_appliance,omitempty"`
	// Client-id of the password grant OAuth client
	ClientId string `json:"client_id,omitempty"`
}
