/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BulkProblemFetchResponse struct for BulkProblemFetchResponse
type BulkProblemFetchResponse struct {
	Results []ProblemWithTime `json:"results,omitempty"`
}
