/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// TopTalkingPairData struct for TopTalkingPairData
type TopTalkingPairData struct {
	SortCriteria TopTalkerSortEnum `json:"sort_criteria,omitempty"`
	SortedList PagedEntityPairListResponse `json:"sorted_list,omitempty"`
}
