/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// UserDefinedProblemEventAllOf struct for UserDefinedProblemEventAllOf
type UserDefinedProblemEventAllOf struct {
	TotalCount int64 `json:"total_count,omitempty"`
	RefsAddedCount int64 `json:"refs_added_count,omitempty"`
	RefsDeletedCount int64 `json:"refs_deleted_count,omitempty"`
	Subscriptions []Reference `json:"subscriptions,omitempty"`
}
