/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NodeType the model 'NodeType'
type NodeType string

// List of NodeType
const (
	NODETYPE_NODE NodeType = "Node"
)
