/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// GroupWithValue struct for GroupWithValue
type GroupWithValue struct {
	Bucket []BucketValue `json:"bucket,omitempty"`
	// count of entity in group
	Count int64 `json:"count,omitempty"`
	Aggregations []AggregationWithValue `json:"aggregations,omitempty"`
}
