/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AppliedTo struct for AppliedTo
type AppliedTo struct {
	ReferredEntity EntityId `json:"referred_entity,omitempty"`
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
	VendorType string `json:"vendor_type,omitempty"`
}
