/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxvManagerDataSourceRequest struct for NsxvManagerDataSourceRequest
type NsxvManagerDataSourceRequest struct {
	// IP address of data source (use either IP or FQDN, not both)
	Ip string `json:"ip,omitempty"`
	// Hostname of data source (use either IP or FQDN, not both)
	Fqdn string `json:"fqdn,omitempty"`
	// ID of Collector VM which should register this vcenter
	ProxyId string `json:"proxy_id"`
	// A friendly nickname for the data source
	Nickname string `json:"nickname"`
	// Whether or not data collection is enabled
	Enabled bool `json:"enabled,omitempty"`
	// Room for notes or comments about the data source
	Notes string `json:"notes,omitempty"`
	Credentials PasswordCredentials `json:"credentials"`
	// Associated vcenter data source entity ID
	VcenterId string `json:"vcenter_id"`
	// Whether or not to configure NSX-v to send IPFIX to vRNI
	IpfixEnabled bool `json:"ipfix_enabled,omitempty"`
	// Whether or not collection via the Central CLI for ESG data is enabled
	CentralCliEnabled bool `json:"central_cli_enabled,omitempty"`
	// Whether or not to configure NSX-v to send virtual infrastructure latency metrics to vRNI
	LatencyEnabled bool `json:"latency_enabled,omitempty"`
}
