/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AppFlowPropEnum the model 'AppFlowPropEnum'
type AppFlowPropEnum string

// List of AppFlowPropEnum
const (
	APPFLOWPROPENUM_FLOW_COUNT AppFlowPropEnum = "FLOW_COUNT"
	APPFLOWPROPENUM_UNPROTECTED_FLOWS AppFlowPropEnum = "UNPROTECTED_FLOWS"
	APPFLOWPROPENUM_DROPPED_FLOWS AppFlowPropEnum = "DROPPED_FLOWS"
	APPFLOWPROPENUM_INTERNET_FLOWS AppFlowPropEnum = "INTERNET_FLOWS"
)
