/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// FetchRequest struct for FetchRequest
type FetchRequest struct {
	EntityIds []FetchRequestEntityIds `json:"entity_ids,omitempty"`
}
