/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// DetailedVendorInfoAllOf struct for DetailedVendorInfoAllOf
type DetailedVendorInfoAllOf struct {
	Manager VendorInfoWithMk `json:"manager,omitempty"`
}
