/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// AzureVmAllOf struct for AzureVmAllOf
type AzureVmAllOf struct {
	Vnet Reference `json:"vnet,omitempty"`
	// The Azure region this VM is hosted
	Region string `json:"region,omitempty"`
	Subscription Reference `json:"subscription,omitempty"`
}
