/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// K8SCredentials struct for K8SCredentials
type K8SCredentials struct {
	// Configuration used to connect to Kubernetes. Can be found in ~/.kube/config
	Kubeconfig string `json:"kubeconfig"`
}
