/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VlanL2Network struct for VlanL2Network
type VlanL2Network struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	NetworkAddresses []string `json:"network_addresses,omitempty"`
	Gateways []string `json:"gateways,omitempty"`
	VlanId string `json:"vlan_id,omitempty"`
	DistributedVirtualSwitches []Reference `json:"distributed_virtual_switches,omitempty"`
	DistributedVirtualPortgroups []Reference `json:"distributed_virtual_portgroups,omitempty"`
}
