/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxPolicyManager struct for NsxPolicyManager
type NsxPolicyManager struct {
	// Entity ID that can be references in detail API calls
	EntityId string `json:"entity_id,omitempty"`
	// Name of the object
	Name string `json:"name,omitempty"`
	EntityType EntityType `json:"entity_type,omitempty"`
	IpAddress IpV4Address `json:"ip_address,omitempty"`
	DataSource Reference `json:"data_source,omitempty"`
	Fqdn string `json:"fqdn,omitempty"`
	EnforcementPoints []Reference `json:"enforcement_points,omitempty"`
	SddcType SddcType `json:"sddc_type,omitempty"`
	Sddc Reference `json:"sddc,omitempty"`
}
