/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// ProxyProfileIdResponse struct for ProxyProfileIdResponse
type ProxyProfileIdResponse struct {
	// Entity Identifier created for the newly configured web proxy server
	ProxyId string `json:"proxy_id,omitempty"`
}
