/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// LicensingKeyRequest license request object
type LicensingKeyRequest struct {
	LicenseKey string `json:"licenseKey,omitempty"`
}
