/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PagedApplicationListResponse struct for PagedApplicationListResponse
type PagedApplicationListResponse struct {
	// Array of returned applications
	Results []Application `json:"results,omitempty"`
	// Cursor for the next page
	Cursor string `json:"cursor,omitempty"`
	// Total number of objects in the system, despite the page limit
	TotalCount int32 `json:"total_count,omitempty"`
}
