/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// BackupSchedulePeriod Backup Schedule period.
type BackupSchedulePeriod string

// List of BackupSchedulePeriod
const (
	BACKUPSCHEDULEPERIOD_DAILY BackupSchedulePeriod = "DAILY"
	BACKUPSCHEDULEPERIOD_WEEKLY BackupSchedulePeriod = "WEEKLY"
)
