/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// TopTalkingMemberData struct for TopTalkingMemberData
type TopTalkingMemberData struct {
	SortCriteria TopTalkerSortEnum `json:"sort_criteria,omitempty"`
	SortedList PagedListResponse `json:"sorted_list,omitempty"`
}
