/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// CiscoSwitchType The Cisco switch model type
type CiscoSwitchType string

// List of CiscoSwitchType
const (
	CISCOSWITCHTYPE_CATALYST_3000 CiscoSwitchType = "CATALYST_3000"
	CISCOSWITCHTYPE_CATALYST_4500 CiscoSwitchType = "CATALYST_4500"
	CISCOSWITCHTYPE_CATALYST_6500 CiscoSwitchType = "CATALYST_6500"
	CISCOSWITCHTYPE_NEXUS_5_K CiscoSwitchType = "NEXUS_5K"
	CISCOSWITCHTYPE_NEXUS_6_K CiscoSwitchType = "NEXUS_6K"
	CISCOSWITCHTYPE_NEXUS_7_K CiscoSwitchType = "NEXUS_7K"
	CISCOSWITCHTYPE_NEXUS_9_K CiscoSwitchType = "NEXUS_9K"
	CISCOSWITCHTYPE_CISCOASRISR CiscoSwitchType = "CISCOASRISR"
)
