/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxtipSetAllOf struct for NsxtipSetAllOf
type NsxtipSetAllOf struct {
	NsxtManagers []Reference `json:"nsxt_managers,omitempty"`
}
