/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SubscriptionListResponse struct for SubscriptionListResponse
type SubscriptionListResponse struct {
	Results []SubscriptionResponse `json:"results,omitempty"`
	TotalCount int32 `json:"total_count,omitempty"`
}
