/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// Ec2SgFirewallRuleAllOf struct for Ec2SgFirewallRuleAllOf
type Ec2SgFirewallRuleAllOf struct {
	Vpc Reference `json:"vpc,omitempty"`
	Direction Ec2FirewallDirection `json:"direction,omitempty"`
	OwnerSecurityGroup Reference `json:"owner_security_group,omitempty"`
}
