/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// EntityNameAllOf struct for EntityNameAllOf
type EntityNameAllOf struct {
	Name string `json:"name,omitempty"`
}
