/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// PksDataSourceRequestAllOf struct for PksDataSourceRequestAllOf
type PksDataSourceRequestAllOf struct {
	Credentials PasswordCredentials `json:"credentials"`
	// Associated NSX-T Manager data source entity ID
	ManagerId string `json:"manager_id"`
}
