/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// GroupMembershipCriteria EntityType currently restricted to VirtualMachine
type GroupMembershipCriteria struct {
	MembershipType string `json:"membership_type,omitempty"`
	IpAddressMembershipCriteria IpAddressMembershipCriteria `json:"ip_address_membership_criteria,omitempty"`
	SearchMembershipCriteria SearchMembershipCriteria `json:"search_membership_criteria,omitempty"`
}
