/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SearchMembershipCriteria struct for SearchMembershipCriteria
type SearchMembershipCriteria struct {
	EntityType AllEntityType `json:"entity_type,omitempty"`
	// As defined in search end point
	Filter string `json:"filter,omitempty"`
}
