/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// RecommendedRules struct for RecommendedRules
type RecommendedRules struct {
	Results []RecommendedRule `json:"results,omitempty"`
	TimeRange TimeRange `json:"time_range,omitempty"`
}
