/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// VidmToken struct for VidmToken
type VidmToken struct {
	// User access token provided by VMware Identity Manager.
	VidmToken string `json:"vidm_token,omitempty"`
}
