/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxControllerClusterAllOf struct for NsxControllerClusterAllOf
type NsxControllerClusterAllOf struct {
	Manager Reference `json:"manager,omitempty"`
	Controllers []Reference `json:"controllers,omitempty"`
}
