/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// IpNumericRange struct for IpNumericRange
type IpNumericRange struct {
	Start int64 `json:"start,omitempty"`
	End int64 `json:"end,omitempty"`
}
