/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// EntityUsingOrBehindWebProxyList struct for EntityUsingOrBehindWebProxyList
type EntityUsingOrBehindWebProxyList struct {
	Results []EntityUsingOrBehindWebProxyResponse `json:"results,omitempty"`
}
