/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// SnmpProfileIds struct for SnmpProfileIds
type SnmpProfileIds struct {
	SnmpProfiles []string `json:"snmp_profiles,omitempty"`
}
