/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NsxtManagerDataSourceRequest struct for NsxtManagerDataSourceRequest
type NsxtManagerDataSourceRequest struct {
	// IP address of data source (use either IP or FQDN, not both)
	Ip string `json:"ip,omitempty"`
	// Hostname of data source (use either IP or FQDN, not both)
	Fqdn string `json:"fqdn,omitempty"`
	// ID of Collector VM which should register this vcenter
	ProxyId string `json:"proxy_id"`
	// A friendly nickname for the data source
	Nickname string `json:"nickname"`
	// Whether or not data collection is enabled
	Enabled bool `json:"enabled,omitempty"`
	// Room for notes or comments about the data source
	Notes string `json:"notes,omitempty"`
	Credentials PasswordCredentials `json:"credentials"`
	// Whether or not to configure NSX-T to send IPFIX to vRNI
	IpfixEnabled bool `json:"ipfix_enabled,omitempty"`
	// Whether or not to configure NSX-T to send virtual infrastructure latency metrics to vRNI
	LatencyEnabled bool `json:"latency_enabled,omitempty"`
	// Whether or not to configure NSX Intelligence to send additional traffic information to vRNI
	NsxiEnabled bool `json:"nsxi_enabled,omitempty"`
}
