/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// FirewallAction the model 'FirewallAction'
type FirewallAction string

// List of FirewallAction
const (
	FIREWALLACTION_ALLOW FirewallAction = "ALLOW"
	FIREWALLACTION_ACCEPT FirewallAction = "ACCEPT"
	FIREWALLACTION_DENY FirewallAction = "DENY"
	FIREWALLACTION_DROP FirewallAction = "DROP"
	FIREWALLACTION_REJECT FirewallAction = "REJECT"
	FIREWALLACTION_REDIRECT FirewallAction = "REDIRECT"
	FIREWALLACTION_DO_NOT_REDIRECT FirewallAction = "DO_NOT_REDIRECT"
)
