/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// NamesResponse struct for NamesResponse
type NamesResponse struct {
	Entities []EntityName `json:"entities,omitempty"`
}
