/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// FirewallRuleSet struct for FirewallRuleSet
type FirewallRuleSet struct {
	FirewallEntityId Reference `json:"firewall_entity_id,omitempty"`
	VendorInfo VendorInfo `json:"vendor_info,omitempty"`
	Manager Reference `json:"manager,omitempty"`
	Rules []BaseFirewallRule `json:"rules,omitempty"`
}
