/*
 * vRealize Network Insight API Reference
 *
 * vRealize Network Insight API Reference
 *
 * API version: 1.1.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vrni
// WanConfig struct for WanConfig
type WanConfig struct {
	// Site name of the WAN router
	Site string `json:"site,omitempty"`
	// Region name of the WAN router
	Region string `json:"region,omitempty"`
	// Interface mappings for MPLS, INTERNET, or OTHER connections
	Interfaces []InterfaceWanConfig `json:"interfaces,omitempty"`
}
